### ISSUE TITLE
Blog report: Download pages problem

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-website#260]
[This comment](https://blog.adoptopenjdk.net/2017/09/openj9_builds#comment-3) was left by Ryan on the AdoptOpenJDK blog on 13th June 2018 at 5:39 am (unknown timezone)

> There seems to be a problem with the download pages. If you switch to anything
> other than version 8, the page hangs with a JavaScript error. Thus, the download 
> links don’t work for anything other than OpenJDK 8. It affects FireFox, Chrome and
> Safari.

**Comment by karianna** [comment]
I've asked Ryan to post the JS error he's seeing.

**Comment by kgibm** [comment]
I can reproduce this. I'm using Firefox 52.8.0 x64 on RHEL 7.5. It happens on Chrome as well. First note is that when I first load https://adoptopenjdk.net/releases.html, I see an HTTP 404 for https://raw.githubusercontent.com/AdoptOpenJDK/openjdk8-releases/master/jck.json. This is an XHR failure in the console:

`GET XHR https://raw.githubusercontent.com/AdoptOpenJDK/openjdk8-releases/master/jck.json`

Immediately after that, I see two errors in the console:

```
XML Parsing Error: syntax error
Location: https://raw.githubusercontent.com/AdoptOpenJDK/openjdk8-releases/master/jck.json
Line Number 1, Column 1:
```

The above isn't surprising since it's a 404 response. And the following which may be related:

```
TypeError: document.getElementById(...) is null
buildLatestHTML https://adoptopenjdk.net/dist/js/app.min-05fc0a2e.js:1:19332
populateLatest/</</< https://adoptopenjdk.net/dist/js/app.min-05fc0a2e.js:1:16824
loadJSON/i.onreadystatechange https://adoptopenjdk.net/dist/js/app.min-05fc0a2e.js:1:2091
```

Now, back to the actual problem, when switching releases and it fails to switch, there's the following error in the console:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
populateLatest/</< https://adoptopenjdk.net/dist/js/app.min-05fc0a2e.js:1:16733
loadJSON/i.onreadystatechange https://adoptopenjdk.net/dist/js/app.min-05fc0a2e.js:1:1448
```

Looking around, I see an XHR request for:

`GET XHR https://raw.githubusercontent.com/AdoptOpenJDK/openjdk9-openj9-releases/master/latest_release.json`

And the network inspector shows that the response content is:

`undefined`

This is verified by just going to that page in the browser.

**Comment by karianna** [comment]
@kgibm Brilliant - thank you!  I suspect this has happened because we removed old unstable release builds and are just starting to repopulate - but we'll double check these

**Comment by karianna** [comment]
The missing JCK file has been fixed by a site redeploy. the missing release.json files works as expected (if there is no release for that variant / platform then that file does not exist).

**Comment by kgibm** [comment]
I just tried this again and I still see the same problem. The AJAX request on https://raw.githubusercontent.com/AdoptOpenJDK/openjdk9-openj9-releases/master/latest_release.json is still returning `undefined`.

**Comment by gdams** [comment]
@kgibm it's meant to be undefined because there is no official release of openjdk9-openj9. You can use the nightly builds for now. The JCK file is also not required.

**Comment by kgibm** [comment]
@gdams I see ok. In any case, then maybe there's another problem because I still can't switch to another release to download it (the ellipses gif just shows indefinitely). Glad to run any debug y'all would like.

**Comment by karianna** [comment]
Hi @kgibm it would be interesting if you could open up developer tools and see which request is hanging the whole page.  I've been unable to reproduce it so far (Chrome, Safari, FF, Opera on Mac)

**Comment by gdams** [comment]
@kgibm what page are you on when you are seeing this?

**Comment by kgibm** [comment]
@gdams Ok, so that's the behavior I see. Shouldn't it show some sort of "No releases" text instead of an indefinite ellipses? I didn't realize that this is expected behavior since there are no releases for those versions yet.

![screenshot from 2018-06-19 07-51-52](https://user-images.githubusercontent.com/6618433/41605281-f88148f4-7395-11e8-885f-ce2c856ec6ef.png)

**Comment by kgibm** [comment]
@karianna All requests complete, but the ellipses just keeps showing (see previous comment).

**Comment by karianna** [comment]
Ok I can reproduce that as well - so yes we should put in some no releases text there.

**Comment by kgibm** [comment]
One additional thought is that the text could be something like, "No official releases yet. See Nightly builds for alternatives", just in case some people might not notice the Nightly builds button
